### ISSUE TITLE
Fabric-api is compatibility error

### ISSUE THREAD

**Issue by MCLombax** [Benjamin-Norton/MCGPT#12]
Mcchatgpt cannot find fabric-api-0.58.0+1.18.2, here is a full error message:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
- Install fabric-api, any version.
Unmet dependency listing:
- Mod 'MCChatGPT' (mcchatgpt) 0.2.0 requires any version of fabric-api, which is missing!
at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Bawnorton** [comment]
that version is over a year old, update your fabric api.

**Comment by MCLombax** [comment]
I have many mods requires specifed version of fabric-api
